---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "eighteen-app-api-test.fullname" . }}
  labels:
    app: {{ template "eighteen-app-api-test.name" . }}
    chart: {{ template "eighteen-app-api-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.eighteen_app_api_test.services.nginx.type }}
  ports:
    - port: {{ .Values.eighteen_app_api_test.services.nginx.httpPort.servicePort }}
      targetPort: {{ .Values.eighteen_app_api_test.services.nginx.httpPort.containerPort }}
  selector:
    app: {{ template "eighteen-app-api-test.name" . }}
    release: {{ .Release.Name }}
