---

apiVersion: spv.no/v1alpha1

kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from env injector
  name: prometheus-secrets
  namespace: monitoring
spec:
  vault:
    # Name of the Azure Keyvault
    name: dpt-services-prod-kv
    object:
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-secrets-prometheus
      type: secret
  output:
    secret:
      # Name of the secret in Kubernetes
      name: prometheus-secrets
      dataKey: alertmanager.yaml
