---

apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    azure-key-vault-env-injection: enabled

---

apiVersion: v1
kind: Namespace
metadata:
  name: dashboards
  labels:
    azure-key-vault-env-injection: enabled
