
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-standard
reclaimPolicy: Retain
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
  kind: Managed

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-premium
reclaimPolicy: Retain
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Premium_LRS
  kind: Managed
