---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certs-anpr-italia-it.fullname" . }}-nginx-configmap
  labels:
    app: {{ template "certs-anpr-italia-it.name" . }}
    chart: {{ template "certs-anpr-italia-it.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cloud_italia_it.conf: {{ toYaml .Values.certs_anpr_italia_it.nginx_config | indent 4 }}
