---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "cla-assistant.fullname" . }}
  labels:
    app: {{ template "cla-assistant.name" . }}
    chart: {{ template "cla-assistant.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.cla_assistant.services.cla_assistant.type }}
  ports:
    - port: {{ .Values.cla_assistant.services.cla_assistant.httpPort.servicePort }}
      targetPort: {{ .Values.cla_assistant.services.cla_assistant.httpPort.containerPort }}
  selector:
    app: {{ template "cla-assistant.name" . }}
    release: {{ .Release.Name }}
