---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "eighteen-app-spid-testenv.fullname" . }}-http
  labels:
    app: {{ template "eighteen-app-spid-testenv.name" . }}
    chart: {{ template "eighteen-app-spid-testenv.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.spidTestenv.services.httpPort.type }}
  ports:
    - name: http-port
{{ toYaml .Values.spidTestenv.services.httpPort | indent 6 }}
  selector:
    app: {{ template "eighteen-app-spid-testenv.name" . }}
    release: {{ .Release.Name }}
